### ISSUE TITLE
Missing configuration files

### ISSUE THREAD

**Issue by honestleaf** [violentmonkey/generator-userscript#1]
After executing `npx -p https://github.com/violentmonkey/generator-userscript.git -p yo yo @violentmonkey/userscript`, I found most configuration files are missing.

Then I did a little research and found the source of the problem:

https://github.com/violentmonkey/generator-userscript/blob/4ddcda510ba8a11b489a97802552562a9e99bd23/lib/generators/app/index.js#L9

Currently, globby treats backslashes as escaping characters. On Windows OS, the `templatePath` function returns file paths with backslashes, which prevent the script from working correctly.

**Comment by gera2ld** [comment]
Thanks!
