### ISSUE TITLE
cant use react's useeffect, usestate

### ISSUE THREAD

**Issue by WiLuX-Source** [violentmonkey/generator-userscript#10]
Hello there,

I'm using this template in my project with my modifications on it for my convenience, any idea why my userscript gives error when i try to use react api?

https://gist.github.com/WiLuX-Source/fd9ac9164ea889f809c20e4a467f9641

**Comment by gera2ld** [comment]
Because React is not supported by default. You need to modify babel and rollup config accordingly to support React.
