### ISSUE TITLE
Bypass CSP?

### ISSUE THREAD

**Issue by DarkHole1** [violentmonkey/generator-userscript#14]
At some point, this template moved from adapting SolidJS to importing UMD directly. But now it can't load on pages with CSP. Any workaround?

**Comment by gera2ld** [comment]
The workaround is to not import it via ESM and bundle it in the script (remove `solid-js` from `external` in `rollup.config.mjs`), but it will blow up the bundle size significantly.

**Comment by DarkHole1** [comment]
That work, thanks!
