### ISSUE TITLE
TypeError: web.template is not a function

### ISSUE THREAD

**Issue by drygoatair** [violentmonkey/generator-userscript#16]
Userscripts created with generator-userscript do not work and throw the following error:

```
TypeError: web.template is not a function
```

To reproduce, simply install `generator-userscript` and build the default `awesome-script`.

**Comment by gera2ld** [comment]
Sorry my bad, wrong global name.

**Comment by drygoatair** [comment]
@gera2ld It seems that the global variable for `solid-js/store` is missing, too:
```
(!) Missing global variable name
https://rollupjs.org/configuration-options/#output-globals
Use "output.globals" to specify browser global variable names corresponding to external modules:
solid-js/store (guessing "store")
```

**Comment by gera2ld** [comment]
`solid-js/store` is never supported in `@violentmonkey/dom`.
Maybe you can just remove `solid-js` from externals so that it gets bundled in the userscript.

**Comment by drygoatair** [comment]
Alright, will do. Thanks!
