### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by bossanovaorca** [violentmonkey/generator-userscript#18]
hello! is there any interest in modifying the generator to create a monorepo where users can develop multiple userscripts in the same repo?

**Comment by gera2ld** [comment]
It already supports multiple scripts in the same repo, but not necessarily a monorepo, because each script is just a separate entry, and they don't depend on each other.

So all you need is to create `src/another-script/index.ts`, and add it to `rollup.config.mjs`:

```diff
  Object.entries({
    'awesome-script':` 'src/awesome-script/index.ts',
+   'another-script': 'src/another-script/index.ts',
  })
```
