### ISSUE TITLE
The new version of TypeScript supports a configuration error with JSX

### ISSUE THREAD

**Issue by fjxhkj** [violentmonkey/generator-userscript#2]
Please change the `JSX` setting in the default `tsconfig.json` file to:

```
"compilerOptions": {
  ...
  "jsx": "react-native", // Or `preserve` but NOT `react`
  ...
}
```

to fix the problem.

You can refer to this:

https://www.typescriptlang.org/tsconfig#jsx

**Comment by gera2ld** [comment]
Can you describe what the problem really is or provide a minimal reproduction?
I cannot reproduce it and a freshly generated TypeScript project works for me.

**Comment by fjxhkj** [comment]
You're right, it does work for now, so maybe you can ignore it.
The reason I found it is because WebStorm has some error warnings.
I think we should ignore it for the time being.
