### ISSUE TITLE
Yarn vs PNPM

### ISSUE THREAD

**Issue by Christopher-Hayes** [violentmonkey/generator-userscript#8]
I installed with the `npx` script, got a `pnpm` lockfile and a README with `yarn` commands in it. Was a little confused what I should be using, lol. In the case where the lockfile is `pnpm-lock.yaml`, the README should probably be showing `pnpm` scripts right?

Used the NPX command [from the docs](https://violentmonkey.github.io/guide/using-modern-syntax/) to init the project. NPM version is `v8.11.0`. I did also have to install PNPM, initially the init script failed because I didn't have PNPM. Might be need to be added to the doc linked above under "Prerequisites".

**Comment by gera2ld** [comment]
`pnpm` should not be required, it's only used when it is detected. It's a bug if an error is thrown, sorry about that.

Using which tool to start the commands actually doesn't matter, maybe I should just change to `npm` since everyone must have at least `npm` installed.
